### PR TITLE
Add a test that creates a new bodhi update.

### PR DESCRIPTION
**Pull request by lmacken**
This tests the python-bugzilla, pkgdb2, and koji staging codepaths.

### CODE REVIEW

**Comment by lmacken** [comment]
I'm curious if this test works for non-provenpackagers.

**Comment by pypingou** [comment]
Code looks fine to me but I did not run it (and I am provenpackager anyway so that would not answer your question :))

**Comment by ralphbean** [comment]
This fails for me:  "ralph is not a proven-packager"

**Comment by ralphbean** [comment]
@lmacken good idea!  http://da.gd/jVOZN

**Comment by lmacken** [comment]
> This fails for me: "ralph is not a proven-packager"

Can you try again? I just added 'packager' to the bodhi admin groups in staging.

**Comment by ralphbean** [comment]
Worked!  That's an awesome test case.

Thanks @lmacken!

**Pull request merged**
