### PR TITLE
Make @rube.tolerant try to clean up before retrying.

### PR DESCRIPTION
**Pull request by ralphbean**

### CODE REVIEW

**Comment by pypingou** [comment]
No print of the exception or so?

Otherwise :+1:

**Comment by ralphbean** [comment]
Yeah, I dunno.  Could be confusing if an exception is printed during exception handling.  Could be even more confusing if no exception is printed...

**Comment by ralphbean** [comment]
Ah, as it stands now this doesn't actually work.  It took writing the following example to figure out why:

``` python
from functools import wraps


def wrapped(func):
    @wraps(func)
    def newfunc(*args, **kwargs):
        print "At this point, I would expect func"
        print "to be a BoundMethod.. but its not."
        print type(func), hasattr(func, 'im_self')
        print "instead, we have to access it as"
        print "args[0]", args[0]
        result = func(*args, **kwargs)
        return result
    return newfunc


class Foo(object):

    def f(self):
        print "f called"

    @wrapped
    def g(self):
        print "g called"


if __name__ == '__main__':
    obj = Foo()
    obj.f()
    obj.g()
```

**Comment by lmacken** [comment]
``` python
ERROR: test_self.test_tolerant
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lmacken/code/github.org/rube/rube-env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/lmacken/code/github.org/rube/rube-env/lib/python2.7/site-packages/nose/tools/nontrivial.py", line 60, in newfunc
    func(*arg, **kw)
TypeError: newfunc() takes at least 1 argument (0 given)
```

**Comment by ralphbean** [comment]
I wasn't able to duplicate it off the bat.  All tests passed:

I'll try again with a fresh venv.

```
(rube)243(377) --- rube/rube.fedora ‹feature/tolerant-cleanup➔› » nosetests
test_title (rube.fedora.test_askbot.TestAskbot) ... ok
test_title (rube.fedora.test_basepage.TestBasePage) ... ok
test_stuff (rube.fedora.test_blockerbugs.TestBlockerBugs) ... ok
test_title (rube.fedora.test_blockerbugs.TestBlockerBugs) ... ok
test_login (rube.fedora.test_bodhi.TestBodhi) ... ok
test_login_bad (rube.fedora.test_bodhi.TestBodhi) ... ok
test_title (rube.fedora.test_bodhi.TestBodhi) ... ok
test_update_comment (rube.fedora.test_bodhi.TestBodhi) ... ok
test_update_view (rube.fedora.test_bodhi.TestBodhi) ... ok
test_title (rube.fedora.test_busmon.TestBusmon) ... ok
test_app01_page (rube.fedora.test_collectd.TestCollectd) ... ok
test_title (rube.fedora.test_collectd.TestCollectd) ... ok
test_title (rube.fedora.test_docs.TestDocs) ... ok
test_title (rube.fedora.test_easyfix.TestEasyFix) ... ok
test_login (rube.fedora.test_elections.TestElections) ... ok
test_title (rube.fedora.test_elections.TestElections) ... ok
test_login_and_edit_account (rube.fedora.test_fas.TestFas) ... ok
test_title (rube.fedora.test_fas.TestFas) ... ok
test_title (rube.fedora.test_haproxy.TestHAProxy) ... ok
test_title (rube.fedora.test_koji.TestKoji) ... ok
test_title (rube.fedora.test_nagios.TestNagios) ... ok
test_search (rube.fedora.test_packages.TestPackages) ... ok
test_title (rube.fedora.test_packages.TestPackages) ... ok
test_paste (rube.fedora.test_paste.TestFPaste) ... ok
test_title (rube.fedora.test_paste.TestFPaste) ... ok
test_login_request_acls (rube.fedora.test_pkgdb.TestPkgDb) ... ok
test_search_for_nethack (rube.fedora.test_pkgdb.TestPkgDb) ... ok
test_title (rube.fedora.test_pkgdb.TestPkgDb) ... ok
test_title (rube.fedora.test_pkgs.TestPkgs) ... ok
test_login_and_edit (rube.fedora.test_wiki.TestWiki) ... ok
test_title (rube.fedora.test_wiki.TestWiki) ... ok

rube.fedora.test_paste.TestFPaste.test_title: 0.3353s
rube.fedora.test_packages.TestPackages.test_title: 0.3940s
rube.fedora.test_easyfix.TestEasyFix.test_title: 0.5880s
rube.fedora.test_elections.TestElections.test_title: 0.9579s
rube.fedora.test_blockerbugs.TestBlockerBugs.test_title: 1.2651s
rube.fedora.test_collectd.TestCollectd.test_title: 1.3109s
rube.fedora.test_wiki.TestWiki.test_title: 1.4630s
rube.fedora.test_docs.TestDocs.test_title: 1.5654s
rube.fedora.test_haproxy.TestHAProxy.test_title: 2.0733s
rube.fedora.test_nagios.TestNagios.test_title: 2.1004s
rube.fedora.test_pkgs.TestPkgs.test_title: 2.3794s
rube.fedora.test_koji.TestKoji.test_title: 2.7579s
rube.fedora.test_pkgdb.TestPkgDb.test_title: 3.7350s
rube.fedora.test_bodhi.TestBodhi.test_login_bad: 4.6217s
rube.fedora.test_fas.TestFas.test_title: 5.3328s
rube.fedora.test_bodhi.TestBodhi.test_title: 6.3495s
rube.fedora.test_askbot.TestAskbot.test_title: 6.4439s
rube.fedora.test_elections.TestElections.test_login: 6.7932s
rube.fedora.test_pkgdb.TestPkgDb.test_search_for_nethack: 8.0773s
rube.fedora.test_packages.TestPackages.test_search: 8.5680s
rube.fedora.test_busmon.TestBusmon.test_title: 8.7374s
rube.fedora.test_bodhi.TestBodhi.test_login: 9.0497s
rube.fedora.test_bodhi.TestBodhi.test_update_view: 11.1062s
rube.fedora.test_blockerbugs.TestBlockerBugs.test_stuff: 11.9603s
rube.fedora.test_paste.TestFPaste.test_paste: 12.1176s
rube.fedora.test_collectd.TestCollectd.test_app01_page: 13.4204s
rube.fedora.test_wiki.TestWiki.test_login_and_edit: 13.7477s
rube.fedora.test_fas.TestFas.test_login_and_edit_account: 14.7351s
rube.fedora.test_bodhi.TestBodhi.test_update_comment: 20.4142s
rube.fedora.test_basepage.TestBasePage.test_title: 22.5293s
rube.fedora.test_pkgdb.TestPkgDb.test_login_request_acls: 25.4025s
----------------------------------------------------------------------
Ran 31 tests in 230.496s

OK
```

**Comment by ralphbean** [comment]
Ok, I was able to duplicate the error in a fresh venv.  Here's the diff of what I had installed a la `pip freeze`:

``` diff
5c5
< nose-testconfig==0.9
---
> nose-testconfig==0.8
10,11c10,12
< scriptine==0.2.0
< selenium==2.32.0
---
> scriptine==0.2.0a4
> selenium==2.31.0
> termcolor==1.0.1
14c15
< yanc==0.2.4
---
> yanc==0.2.3
```

**Comment by ralphbean** [comment]
Turns out the deps had nothing to do with it.  The above commit should fix it.

**Comment by lmacken** [comment]
That did the trick! :money_with_wings:

**Comment by ralphbean** [comment]
Awesome!  :dancer:

**Pull request merged**
